# Generated by Django 4.2 on 2023-04-27 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['id'], 'verbose_name': 'Postagem', 'verbose_name_plural': 'Postagens'},
        ),
    ]
